# -*- coding: utf-8 -*-
"""ASR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153dKV1P0IjPCwIORnDgXb86pJ57hUNQl
"""

!pip install transformers
!pip install pydub
!pip install soundfile

from transformers import pipeline
from pydub import AudioSegment
import numpy as np
import soundfile as sf
from io import BytesIO
import requests

asr_pipeline = pipeline("automatic-speech-recognition", model="facebook/wav2vec2-large-960h")

from google.colab import files
uploaded = files.upload()

def load_audio(file_path):
    audio, samplerate = sf.read(file_path)
    return audio, samplerate

# Get the uploaded file path
file_path = list(uploaded.keys())[0]

def transcribe_audio(file_path):
    # Load the audio file
    audio, _ = load_audio(file_path)

    # Convert the audio array to a suitable format
    audio = np.array(audio, dtype=np.float32)

    # Transcribe the audio
    result = asr_pipeline(audio)

    return result['text']

# Perform transcription
transcription = transcribe_audio(file_path)
print("Transcription:", transcription)