# -*- coding: utf-8 -*-
"""ASR1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hI9gnCkY-r5zdcnmfEUTVQ4XO4T2fen
"""

!pip install pydub
!pip install librosa
!pip install numpy
!pip install matplotlib
!pip install speechrecognition

!pip install noisereduce

from pydub import AudioSegment
import librosa
import numpy as np
import matplotlib.pyplot as plt
import noisereduce as nr
import IPython.display as ipd
import soundfile as sf

# Upload your audio file to Google Colab
from google.colab import files
uploaded = files.upload()

# Convert the uploaded file to a format suitable for processing
audio_file = list(uploaded.keys())[0]
audio = AudioSegment.from_file(audio_file)

# Convert to wav format (if not already in this format)
audio.export("converted_audio.wav", format="wav")

# Load audio using librosa
y, sr = librosa.load("converted_audio.wav")

# Normalize the audio
y_normalized = librosa.util.normalize(y)

# Noise reduction
y_reduced_noise = nr.reduce_noise(y=y_normalized, sr=sr)

# Save the preprocessed audio
sf.write("preprocessed_audio.wav", y_reduced_noise, sr)

# Play the preprocessed audio
ipd.Audio("preprocessed_audio.wav")

# Visualize the waveform
plt.figure(figsize=(14, 5))
librosa.display.waveshow(y_reduced_noise, sr=sr)
plt.title("Waveform of the Audio")
plt.show()

# Visualize the Spectrogram
D = librosa.amplitude_to_db(np.abs(librosa.stft(y_reduced_noise)), ref=np.max)
plt.figure(figsize=(14, 5))
librosa.display.specshow(D, sr=sr, x_axis='time', y_axis='log')
plt.colorbar(format='%+2.0f dB')
plt.title('Spectrogram')
plt.show()

import speech_recognition as sr

# Initialize recognizer
recognizer = sr.Recognizer()

# Load the preprocessed audio file
audio_file_path = "preprocessed_audio.wav"
with sr.AudioFile(audio_file_path) as source:
    audio_data = recognizer.record(source)
    # Recognize (convert from speech to text)
    try:
        text = recognizer.recognize_google(audio_data)
        print("Recognized Text:")
        print(text)
    except sr.UnknownValueError:
        print("Google Speech Recognition could not understand the audio.")
    except sr.RequestError as e:
        print(f"Could not request results from Google Speech Recognition service; {e}")

from google.colab import files

# Save recognized text
with open("recognized_text.txt", "w") as text_file:
    text_file.write(text)

# Download recognized text
files.download("recognized_text.txt")